export const tvconfig = {
  width: 'auto',
  height: 600,
  symbol: 'FX:EURUSD',
  interval: 'D',
  timezone: 'Etc/UTC',
  theme: 'light',
  style: '1',
  locale: 'en',
  toolbar_bg: '#f1f3f6',
  enable_publishing: false,
  allow_symbol_change: true,
  gridColor: 'rgba(0, 0, 0, 0.06)',
  hide_legend: true,
  withdateranges: true,
  hide_side_toolbar: false,
  save_image: true,
  watchlist: [
    'FX:EURUSD',
    'FX:GBPUSD',
    'USDJPY',
    'FX:USDCHF',
    'FX:USDCAD',
    'FX:AUDUSD',
    'FX:NZDUSD',
  ],
  container_id: 'tradingview_73778',
};
